export interface Product {
  id: string;
  name: string;
  category: string;
  emoji: string;
  price: number;
  description: string;
  featured?: boolean;
  brand?: string;
  imageUrl?: string;
  stock?: number;
  unit?: string;
}

export const categories = [
  { name: 'Books & Notebooks', emoji: '📚' },
  { name: 'Writing Instruments', emoji: '✏️' },
  { name: 'Math Sets & Calculators', emoji: '�' },
  { name: 'Office Supplies', emoji: '📋' },
  { name: 'Storage & Organization', emoji: '🗂️' },
  { name: 'Uniforms & Clothing', emoji: '👔' },
  { name: 'Weather Protection', emoji: '☂️' },
  { name: 'Cleaning Supplies', emoji: '🧹' },
];

export const products: Product[] = [
  // 📚 BOOKS & NOTEBOOKS (17 Products)
  {
    id: '001',
    name: 'Champion Exercise Book (200 pages)',
    category: 'Books & Notebooks',
    emoji: '📚',
    price: 3500,
    description: 'Champion Exercise Book with 200 pages. Perfect for school use.',
    featured: true,
    brand: 'Champion',
    unit: 'piece',
    stock: 50,
    imageUrl: '/images/products/product-001-champion-exercise-book-200.jpg',
  },
  {
    id: '002',
    name: 'Champion Exercise Book (96 pages)',
    category: 'Books & Notebooks',
    emoji: '📚',
    price: 1667,
    description: 'Champion Exercise Book with 96 pages. Good for all subjects.',
    brand: 'Champion',
    unit: 'piece',
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&h=500&fit=crop',
  },
  {
    id: '003',
    name: 'Picfare Exercise Books (96 pages)',
    category: 'Books & Notebooks',
    emoji: '📚',
    price: 833,
    description: 'Picfare Exercise Books with 96 pages. Affordable quality.',
    featured: true,
    brand: 'Picfare',
    unit: 'piece',
    stock: 60,
    imageUrl: '/images/products/product-003-picfare-exercise-book-96.jpg',
  },
  {
    id: '004',
    name: 'Counter Book (192 pages)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 5000,
    description: 'Professional counter book with 192 pages. For keeping records.',
    brand: 'Generic',
    unit: 'piece',
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop',
  },
  {
    id: '005',
    name: 'Counter Book (384 pages)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 7500,
    description: 'Counter book with 384 pages. Durable binding for records.',
    brand: 'Generic',
    unit: 'piece',
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop',
  },
  {
    id: '006',
    name: 'Counter Book (2 Quire)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 5000,
    description: 'Counter book with 2 quires. Suitable for business records.',
    brand: 'Generic',
    unit: 'piece',
    stock: 38,
    imageUrl: '/images/products/product-006-counter-book-2quire.jpg',
  },
  {
    id: '007',
    name: 'Counter Book (3 Quire)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 7000,
    description: 'Counter book with 3 quires. Quality paper and binding.',
    brand: 'Generic',
    unit: 'piece',
    stock: 32,
    imageUrl: '/images/products/product-007-counter-book-3quire.jpg',
  },
  {
    id: '008',
    name: 'Counter Book (4 Quire)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 9000,
    description: 'Large counter book with 4 quires. Professional quality.',
    featured: true,
    brand: 'Generic',
    unit: 'piece',
    stock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop',
  },
  {
    id: '009',
    name: 'Picfare Counter Book (96 pages)',
    category: 'Books & Notebooks',
    emoji: '📒',
    price: 5500,
    description: 'Picfare counter book with 96 pages. Reliable quality.',
    brand: 'Picfare',
    unit: 'piece',
    stock: 42,
    imageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=500&fit=crop',
  },
  {
    id: '010',
    name: 'Picfare Simply the Best (196 pages)',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 5500,
    description: 'Picfare Simply the Best with 196 pages. Popular choice.',
    brand: 'Picfare',
    unit: 'piece',
    stock: 48,
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&h=500&fit=crop',
  },
  {
    id: '011',
    name: 'Picfare Simply the Best (384 pages)',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 8000,
    description: 'Picfare Simply the Best with 384 pages. Excellent value.',
    featured: true,
    brand: 'Picfare',
    unit: 'piece',
    stock: 36,
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&h=500&fit=crop',
  },
  {
    id: '012',
    name: 'Manuscript Book (2 Quire)',
    category: 'Books & Notebooks',
    emoji: '📗',
    price: 10000,
    description: 'Premium manuscript book with 2 quires. High-quality paper.',
    brand: 'Generic',
    unit: 'piece',
    stock: 25,
    imageUrl: '/images/products/product-012-manuscript-2quire.jpg',
  },
  {
    id: '013',
    name: 'Manuscript Book (4 Quire)',
    category: 'Books & Notebooks',
    emoji: '📗',
    price: 15000,
    description: 'Premium manuscript book with 4 quires. Professional quality.',
    brand: 'Generic',
    unit: 'piece',
    stock: 20,
    imageUrl: '/images/products/product-013-manuscript-4quire.jpg',
  },
  {
    id: '014',
    name: 'Graph Book (48 pages)',
    category: 'Books & Notebooks',
    emoji: '📈',
    price: 3000,
    description: 'Graph book with 48 pages. For mathematics and science.',
    brand: 'Generic',
    unit: 'piece',
    stock: 55,
    imageUrl: '/images/products/product-014-graph-book-48.jpg',
  },
  {
    id: '015',
    name: 'Graph Book (96 pages)',
    category: 'Books & Notebooks',
    emoji: '📈',
    price: 4000,
    description: 'Graph book with 96 pages. Quality paper for technical work.',
    featured: true,
    brand: 'Generic',
    unit: 'piece',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=500&h=500&fit=crop',
  },
  {
    id: '016',
    name: 'Short Hand Note Book',
    category: 'Books & Notebooks',
    emoji: '📝',
    price: 2000,
    description: 'Shorthand notebook for quick note-taking. Compact size.',
    brand: 'Generic',
    unit: 'piece',
    stock: 70,
    imageUrl: '/images/products/product-016-shorthand-notebook.jpg',
  },
  {
    id: '017',
    name: 'Premium Note Book',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 20000,
    description: 'Premium notebook with quality binding. Professional appearance.',
    brand: 'Generic',
    unit: 'piece',
    stock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop',
  },

  // ✏️ WRITING INSTRUMENTS (4 Products)
  {
    id: '018',
    name: 'Bic Crystal Pens (Box)',
    category: 'Writing Instruments',
    emoji: '✏️',
    price: 27000,
    description: 'Bic Crystal pens in box. Smooth writing experience.',
    featured: true,
    brand: 'Bic',
    unit: 'box',
    stock: 35,
    imageUrl: '/images/products/product-018-bic-crystal-pens-box.jpg',
  },
  {
    id: '019',
    name: 'Bic Markers',
    category: 'Writing Instruments',
    emoji: '🖍️',
    price: 2000,
    description: 'Bic markers for presentations and artwork. Vibrant colors.',
    brand: 'Bic',
    unit: 'piece',
    stock: 80,
    imageUrl: '/images/products/product-019-bic-markers.jpg',
  },
  {
    id: '020',
    name: 'White Board Markers',
    category: 'Writing Instruments',
    emoji: '🖌️',
    price: 2500,
    description: 'Whiteboard markers with dry-erase formula. Easy to clean.',
    featured: true,
    brand: 'Generic',
    unit: 'piece',
    stock: 90,
    imageUrl: '/images/products/product-020-whiteboard-markers.jpg',
  },
  {
    id: '021',
    name: 'Bic Office Mate Correction',
    category: 'Writing Instruments',
    emoji: '✏️',
    price: 3000,
    description: 'Bic correction pen. Quick and clean corrections.',
    brand: 'Bic',
    unit: 'piece',
    stock: 65,
    imageUrl: '/images/products/product-021-bic-correction.jpg',
  },

  // 🔢 MATHEMATICAL SETS & CALCULATORS (5 Products)
  {
    id: '022',
    name: 'Casio fx 82 MS Calculator',
    category: 'Math Sets & Calculators',
    emoji: '🔢',
    price: 25000,
    description: 'Casio scientific calculator. Essential for mathematics.',
    featured: true,
    brand: 'Casio',
    unit: 'piece',
    stock: 22,
    imageUrl: '/images/products/product-022-casio-calculator-fx82ms.jpg',
  },
  {
    id: '023',
    name: 'Oxford Mathematical Sets',
    category: 'Math Sets & Calculators',
    emoji: '📐',
    price: 10000,
    description: 'Oxford mathematical set with complete tools. Professional quality.',
    featured: true,
    brand: 'Oxford',
    unit: 'set',
    stock: 30,
    imageUrl: '/images/products/product-023-oxford-math-set.jpg',
  },
  {
    id: '024',
    name: 'Nataraj Mathematical Sets',
    category: 'Math Sets & Calculators',
    emoji: '📐',
    price: 8000,
    description: 'Nataraj mathematical set. Reliable and affordable.',
    brand: 'Nataraj',
    unit: 'set',
    stock: 35,
    imageUrl: '/images/products/product-024-nataraj-math-set.jpg',
  },
  {
    id: '025',
    name: 'Picfare Mathematical Sets',
    category: 'Math Sets & Calculators',
    emoji: '📐',
    price: 4000,
    description: 'Picfare mathematical set. Good value for students.',
    brand: 'Picfare',
    unit: 'set',
    stock: 50,
    imageUrl: '/images/products/product-025-picfare-math-set.jpg',
  },
  {
    id: '026',
    name: 'Kofa Mathematical Set',
    category: 'Math Sets & Calculators',
    emoji: '📐',
    price: 4000,
    description: 'Kofa mathematical set. Complete with essential tools.',
    brand: 'Kofa',
    unit: 'set',
    stock: 45,
    imageUrl: '/images/products/product-026-kofa-math-set.jpg',
  },

  // 📋 OFFICE SUPPLIES (5 Products)
  {
    id: '027',
    name: 'Ream of Papers (Double A)',
    category: 'Office Supplies',
    emoji: '📄',
    price: 25000,
    description: 'Ream of Double A papers. High-quality white paper.',
    featured: true,
    brand: 'Double A',
    unit: 'ream',
    stock: 40,
    imageUrl: '/images/products/product-027-double-a-paper-ream.jpg',
  },
  {
    id: '028',
    name: 'Eraser',
    category: 'Office Supplies',
    emoji: '🧹',
    price: 1500,
    description: 'Quality eraser. Clean pencil marks easily.',
    brand: 'Generic',
    unit: 'piece',
    stock: 100,
    imageUrl: '/images/products/product-028-eraser.jpg',
  },
  {
    id: '029',
    name: 'Scissors (Various Sizes)',
    category: 'Office Supplies',
    emoji: '✂️',
    price: 10000,
    description: 'Scissors in various sizes. Sharp and durable.',
    brand: 'Generic',
    unit: 'piece',
    stock: 30,
    imageUrl: '/images/products/product-029-scissors.jpg',
  },
  {
    id: '030',
    name: 'Envelopes (Pack)',
    category: 'Office Supplies',
    emoji: '✉️',
    price: 10000,
    description: 'Pack of envelopes. Various sizes available.',
    brand: 'Generic',
    unit: 'pack',
    stock: 50,
    imageUrl: '/images/products/product-030-envelopes-pack.jpg',
  },
  {
    id: '031',
    name: 'Kangaroo Stapler HD12-17',
    category: 'Office Supplies',
    emoji: '📎',
    price: 15000,
    description: 'Kangaroo stapler. Heavy duty and reliable.',
    brand: 'Kangaroo',
    unit: 'piece',
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500&h=500&fit=crop',
  },
  {
    id: '032',
    name: 'Kangaroo Stapler HP-45',
    category: 'Office Supplies',
    emoji: '📎',
    price: 18000,
    description: 'Kangaroo stapler HP-45. Powerful and durable.',
    brand: 'Kangaroo',
    unit: 'piece',
    stock: 20,
    imageUrl: '/images/products/product-032-kangaroo-stapler-hp45.jpg',
  },

  // 🗂️ STORAGE & ORGANIZATION (3 Products)
  {
    id: '033',
    name: 'Spring Files',
    category: 'Storage & Organization',
    emoji: '📁',
    price: 2500,
    description: 'Spring file for document storage. Secure closure.',
    brand: 'Generic',
    unit: 'piece',
    stock: 70,
    imageUrl: '/images/products/product-033-spring-files.jpg',
  },
  {
    id: '034',
    name: 'Box Files',
    category: 'Storage & Organization',
    emoji: '📦',
    price: 7000,
    description: 'Box file for organizing papers. Durable cardboard.',
    brand: 'Generic',
    unit: 'piece',
    stock: 55,
    imageUrl: '/images/products/product-034-box-files.jpg',
  },
  {
    id: '035',
    name: 'Metallic Box/Case (Various Sizes)',
    category: 'Storage & Organization',
    emoji: '🎁',
    price: 250000,
    description: 'Metallic storage box in various sizes. Durable and secure.',
    brand: 'Generic',
    unit: 'piece',
    stock: 15,
    imageUrl: '/images/products/product-035-metallic-case.jpg',
  },

  // 👔 UNIFORMS & CLOTHING (4 Products)
  {
    id: '036',
    name: 'Caribbean Skirts',
    category: 'Uniforms & Clothing',
    emoji: '👗',
    price: 35000,
    description: 'Caribbean style skirts. Quality fabric and stitching.',
    featured: true,
    brand: 'Generic',
    unit: 'piece',
    stock: 25,
    imageUrl: '/images/products/product-036-caribbean-skirts.jpg',
  },
  {
    id: '037',
    name: 'Girls Socks',
    category: 'Uniforms & Clothing',
    emoji: '🧦',
    price: 7000,
    description: 'Girls socks. Comfortable and durable.',
    brand: 'Generic',
    unit: 'piece',
    stock: 60,
    imageUrl: '/images/products/product-037-girls-socks.jpg',
  },
  {
    id: '038',
    name: 'Men\'s Socks',
    category: 'Uniforms & Clothing',
    emoji: '🧦',
    price: 3000,
    description: 'Men\'s socks. Quality and comfort guaranteed.',
    brand: 'Generic',
    unit: 'piece',
    stock: 85,
    imageUrl: '/images/products/product-038-mens-socks.jpg',
  },
  {
    id: '039',
    name: 'Wrist Watches (All Colors)',
    category: 'Uniforms & Clothing',
    emoji: '⌚',
    price: 15000,
    description: 'Wrist watches in various colors. Stylish and functional.',
    brand: 'Generic',
    unit: 'piece',
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
  },

  // ☂️ WEATHER PROTECTION (3 Products)
  {
    id: '040',
    name: 'Executive Umbrella',
    category: 'Weather Protection',
    emoji: '☂️',
    price: 30000,
    description: 'Executive umbrella. Premium quality and design.',
    featured: true,
    brand: 'Generic',
    unit: 'piece',
    stock: 20,
    imageUrl: '/images/products/product-040-executive-umbrella.jpg',
  },
  {
    id: '041',
    name: 'Stripped Umbrellas',
    category: 'Weather Protection',
    emoji: '☂️',
    price: 20000,
    description: 'Umbrellas with striped pattern. Colorful design.',
    brand: 'Generic',
    unit: 'piece',
    stock: 35,
    imageUrl: '/images/products/product-041-stripped-umbrella.jpg',
  },
  {
    id: '042',
    name: 'Small Portable Umbrella',
    category: 'Weather Protection',
    emoji: '☂️',
    price: 10000,
    description: 'Compact umbrella. Easy to carry in a bag.',
    brand: 'Generic',
    unit: 'piece',
    stock: 50,
    imageUrl: '/images/products/product-042-portable-umbrella.jpg',
  },

  // 🧹 CLEANING SUPPLIES (4 Products)
  {
    id: '043',
    name: 'Ariel Washing Pack (1kg + 3 bars soap)',
    category: 'Cleaning Supplies',
    emoji: '🧴',
    price: 30000,
    description: 'Ariel washing pack with detergent and soap bars. Complete laundry solution.',
    brand: 'Ariel',
    unit: 'pack',
    stock: 32,
    imageUrl: '/images/products/product-043-ariel-washing-pack.jpg',
  },
  {
    id: '044',
    name: 'Duster',
    category: 'Cleaning Supplies',
    emoji: '🧹',
    price: 5000,
    description: 'Quality duster for cleaning blackboards and whiteboards.',
    brand: 'Generic',
    unit: 'piece',
    stock: 45,
    imageUrl: '/images/products/duster.jpeg',
  },
  {
    id: '045',
    name: 'Roll Tissue',
    category: 'Cleaning Supplies',
    emoji: '🧻',
    price: 8000,
    description: 'Roll tissue paper. Soft and absorbent.',
    brand: 'Generic',
    unit: 'roll',
    stock: 60,
    imageUrl: '/images/products/Rolltissue.jpeg',
  },
  {
    id: '046',
    name: 'Toilet Paper Rolls',
    category: 'Cleaning Supplies',
    emoji: '🧻',
    price: 12000,
    description: 'Toilet paper rolls. Quality and comfort.',
    brand: 'Generic',
    unit: 'pack',
    stock: 50,
    imageUrl: '/images/products/toiletpaperolls.jpeg',
  },

  // 📚 BOOKS & NOTEBOOKS (Additional Products)
  {
    id: '047',
    name: 'Atlas',
    category: 'Books & Notebooks',
    emoji: '🗺️',
    price: 25000,
    description: 'World atlas for geography studies. Comprehensive maps and information.',
    brand: 'Generic',
    unit: 'piece',
    stock: 20,
    imageUrl: '/images/products/ATLAS.jpeg',
  },
  {
    id: '048',
    name: 'Atlas Moran',
    category: 'Books & Notebooks',
    emoji: '🗺️',
    price: 28000,
    description: 'Moran atlas with detailed geographical information.',
    brand: 'Moran',
    unit: 'piece',
    stock: 18,
    imageUrl: '/images/products/ATLASM,ORAN.jpeg',
  },
  {
    id: '049',
    name: 'Atlas Secondary',
    category: 'Books & Notebooks',
    emoji: '🗺️',
    price: 22000,
    description: 'Secondary school atlas. Perfect for geography students.',
    brand: 'Generic',
    unit: 'piece',
    stock: 25,
    imageUrl: '/images/products/atlassecondary.jpeg',
  },
  {
    id: '050',
    name: 'Oxford Dictionary',
    category: 'Books & Notebooks',
    emoji: '📖',
    price: 45000,
    description: 'Oxford English dictionary. Comprehensive word definitions.',
    featured: true,
    brand: 'Oxford',
    unit: 'piece',
    stock: 15,
    imageUrl: '/images/products/dictionaryoxford.jpeg',
  },
  {
    id: '051',
    name: 'Oxford Primary Dictionary',
    category: 'Books & Notebooks',
    emoji: '📖',
    price: 35000,
    description: 'Oxford primary dictionary for young learners.',
    brand: 'Oxford',
    unit: 'piece',
    stock: 22,
    imageUrl: '/images/products/oxfordPrimary.jpeg',
  },
  {
    id: '052',
    name: 'Holy Bible',
    category: 'Books & Notebooks',
    emoji: '📿',
    price: 30000,
    description: 'Holy Bible. Quality printing and binding.',
    brand: 'Generic',
    unit: 'piece',
    stock: 30,
    imageUrl: '/images/products/HolyBible.jpeg',
  },
  {
    id: '053',
    name: 'Notebook',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 5000,
    description: 'Quality notebook for writing and note-taking.',
    brand: 'Generic',
    unit: 'piece',
    stock: 55,
    imageUrl: '/images/products/NOTEBOOK.jpeg',
  },
  {
    id: '054',
    name: 'Premium Notebook',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 8000,
    description: 'Premium quality notebook with durable binding.',
    brand: 'Generic',
    unit: 'piece',
    stock: 40,
    imageUrl: '/images/products/notebook (2).jpeg',
  },
  {
    id: '055',
    name: 'Dolphin Premium Notebook',
    category: 'Books & Notebooks',
    emoji: '📓',
    price: 12000,
    description: 'Dolphin premium notebook. High-quality paper and binding.',
    brand: 'Dolphin',
    unit: 'piece',
    stock: 28,
    imageUrl: '/images/products/dolphinpremium.jpeg',
  },
  {
    id: '056',
    name: 'Flip File',
    category: 'Books & Notebooks',
    emoji: '📁',
    price: 15000,
    description: 'Flip file for organizing documents and papers.',
    brand: 'Generic',
    unit: 'piece',
    stock: 35,
    imageUrl: '/images/products/FLIPFILE.jpeg',
  },
  {
    id: '057',
    name: 'School Register',
    category: 'Books & Notebooks',
    emoji: '📋',
    price: 20000,
    description: 'School register for attendance and records.',
    brand: 'Generic',
    unit: 'piece',
    stock: 25,
    imageUrl: '/images/products/schoolregister.jpeg',
  },

  // ✏️ WRITING INSTRUMENTS (Additional Products)
  {
    id: '058',
    name: 'Nataraj Pencils',
    category: 'Writing Instruments',
    emoji: '✏️',
    price: 5000,
    description: 'Nataraj pencils. Quality graphite for smooth writing.',
    featured: true,
    brand: 'Nataraj',
    unit: 'pack',
    stock: 70,
    imageUrl: '/images/products/Nataraj.jpeg',
  },
  {
    id: '059',
    name: 'Pencils',
    category: 'Writing Instruments',
    emoji: '✏️',
    price: 3000,
    description: 'Quality pencils for writing and drawing.',
    brand: 'Generic',
    unit: 'pack',
    stock: 90,
    imageUrl: '/images/products/pencil.jpeg',
  },

  // 🔢 MATHEMATICAL SETS & CALCULATORS (Additional Products)
  {
    id: '060',
    name: 'Casio Calculator',
    category: 'Math Sets & Calculators',
    emoji: '🔢',
    price: 25000,
    description: 'Casio scientific calculator. Essential for mathematics and science.',
    featured: true,
    brand: 'Casio',
    unit: 'piece',
    stock: 25,
    imageUrl: '/images/products/casiocalculator.jpeg',
  },

  // 📋 OFFICE SUPPLIES (Additional Products)
  {
    id: '061',
    name: 'Rotatrim',
    category: 'Office Supplies',
    emoji: '✂️',
    price: 150000,
    description: 'Rotatrim paper cutter. Professional cutting tool.',
    brand: 'Rotatrim',
    unit: 'piece',
    stock: 5,
    imageUrl: '/images/products/rotatrim.jpeg',
  },
  {
    id: '062',
    name: 'Flask',
    category: 'Office Supplies',
    emoji: '🍼',
    price: 12000,
    description: 'Water flask for school. Durable and leak-proof.',
    brand: 'Generic',
    unit: 'piece',
    stock: 40,
    imageUrl: '/images/products/flask.jpeg',
  },
  {
    id: '063',
    name: 'Pegs',
    category: 'Office Supplies',
    emoji: '📎',
    price: 3000,
    description: 'Clothes pegs for hanging. Durable plastic.',
    brand: 'Generic',
    unit: 'pack',
    stock: 80,
    imageUrl: '/images/products/peggs.jpeg',
  },

  // 👔 UNIFORMS & CLOTHING (Additional Products)
  {
    id: '064',
    name: 'Vest',
    category: 'Uniforms & Clothing',
    emoji: '👕',
    price: 15000,
    description: 'School vest. Comfortable and durable fabric.',
    brand: 'Generic',
    unit: 'piece',
    stock: 45,
    imageUrl: '/images/products/vestt.jpeg',
  },
];

export const getProductsByCategory = (category: string) => {
  return products.filter(product => product.category === category);
};

export const getFeaturedProducts = () => {
  return products.filter(product => product.featured);
};

export const searchProducts = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    product =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      (product.brand && product.brand.toLowerCase().includes(lowercaseQuery))
  );
};

// Additional utility functions
export const getProductById = (id: string) => {
  return products.find(product => product.id === id);
};

export const getProductsByPriceRange = (min: number, max: number) => {
  return products.filter(product => product.price >= min && product.price <= max);
};

export const getInStockProducts = () => {
  return products.filter(product => product.stock && product.stock > 0);
};

export const getBrandedProducts = () => {
  return products.filter(product => product.brand && product.brand !== 'Generic');
};